/**
 * Pagefind adapter tests — vendor-specific behavior.
 *
 * The Pagefind bundle is a runtime artefact generated by
 * `pnpm build:pagefind` (post-`next build`). Tests inject a fake
 * loader via `PagefindAdapterOptions.loadModule` so the adapter's
 * normalization logic is exercised without standing up a real bundle.
 *
 * Contract-level behavior (empty-query, abort, pagination, score
 * range) is exercised by the in-memory fake against the same port;
 * this file ONLY covers Pagefind-specific concerns: result-data
 * normalisation, tag-scoping options, bundle-unavailable error
 * surface, lazy loading semantics.
 */

import { describe, expect, it, vi } from 'vitest';
import {
  makePagefindAdapter,
  PagefindBundleUnavailableError,
  type PagefindModule,
} from '../src/adapters/pagefind';

interface MockResultData {
  url: string;
  raw_url?: string;
  excerpt: string;
  meta: {
    title?: string;
    category?: string;
    locale?: string;
  };
}

function makeMockPagefind(results: readonly { id: string; data: MockResultData }[]) {
  const optionsSpy = vi.fn(async (_opts: Record<string, unknown>) => undefined);
  const searchSpy = vi.fn(async (_q: string, _opts?: Record<string, unknown>) => ({
    results: results.map((r) => ({
      id: r.id,
      data: async () => r.data,
    })),
  }));
  const pagefindModule: PagefindModule = { options: optionsSpy, search: searchSpy };
  return { module: pagefindModule, optionsSpy, searchSpy };
}

describe('Pagefind adapter — vendor-specific behaviour', () => {
  it('lazily invokes the loader on first search call', async () => {
    const mock = makeMockPagefind([
      {
        id: 'page-1',
        data: {
          url: '/en/blog/post-1',
          excerpt: 'Excerpt one',
          meta: { title: 'Post one', category: 'blog', locale: 'en' },
        },
      },
    ]);
    const loadModule = vi.fn(async () => mock.module);

    const index = makePagefindAdapter({ loadModule });
    expect(loadModule).not.toHaveBeenCalled();
    expect(mock.searchSpy).not.toHaveBeenCalled();

    const r = await index.search('post');

    expect(loadModule).toHaveBeenCalledTimes(1);
    expect(mock.searchSpy).toHaveBeenCalledTimes(1);
    expect(r.total).toBe(1);
    expect(r.hits[0]?.id).toBe('page-1');
    expect(r.hits[0]?.title).toBe('Post one');
    expect(r.hits[0]?.category).toBe('blog');
  });

  it('reuses the cached module across subsequent searches', async () => {
    const mock = makeMockPagefind([
      {
        id: 'page-1',
        data: {
          url: '/en/post',
          excerpt: 'Excerpt',
          meta: { title: 'Post', category: 'blog', locale: 'en' },
        },
      },
    ]);
    const loadModule = vi.fn(async () => mock.module);

    const index = makePagefindAdapter({ loadModule });
    await index.search('post');
    await index.search('post');
    await index.search('post');

    expect(loadModule).toHaveBeenCalledTimes(1);
    expect(mock.searchSpy).toHaveBeenCalledTimes(3);
  });

  it('throws PagefindBundleUnavailableError when the loader fails', async () => {
    const loadModule = vi.fn(async () => {
      throw new Error('network: 404');
    });

    const index = makePagefindAdapter({ loadModule });
    await expect(index.search('anything')).rejects.toBeInstanceOf(PagefindBundleUnavailableError);
  });

  it('does NOT cache a failed load — a retry can self-heal', async () => {
    let attempts = 0;
    const mock = makeMockPagefind([]);
    const loadModule = vi.fn(async () => {
      attempts += 1;
      if (attempts === 1) throw new Error('transient');
      return mock.module;
    });

    const index = makePagefindAdapter({ loadModule });
    await expect(index.search('q')).rejects.toBeInstanceOf(PagefindBundleUnavailableError);
    // Second call retries the loader (no stuck-failure cache).
    const r = await index.search('q');
    expect(r.total).toBe(0);
    expect(loadModule).toHaveBeenCalledTimes(2);
  });

  it('normalises category to the closed port union (blog/customers/legal/changelog/page)', async () => {
    const mock = makeMockPagefind([
      {
        id: 'unknown-cat',
        data: {
          url: '/x',
          excerpt: 'e',
          meta: { title: 'X', category: 'science', locale: 'en' },
        },
      },
    ]);

    const index = makePagefindAdapter({ loadModule: async () => mock.module });
    const r = await index.search('X');
    expect(r.hits[0]?.category).toBe('page');
  });

  it('falls back to "page" category + "en" locale + "(untitled)" title when meta is partial', async () => {
    const mock = makeMockPagefind([
      {
        id: 'minimal',
        data: { url: '/min', excerpt: 'e', meta: {} },
      },
    ]);

    const index = makePagefindAdapter({ loadModule: async () => mock.module });
    const r = await index.search('e');
    expect(r.hits[0]?.title).toBe('(untitled)');
    expect(r.hits[0]?.locale).toBe('en');
    expect(r.hits[0]?.category).toBe('page');
  });

  it('honours indexTag by setting Pagefind baseFilters via options()', async () => {
    const mock = makeMockPagefind([
      {
        id: 'p',
        data: {
          url: '/p',
          excerpt: 'e',
          meta: { title: 'P', category: 'blog', locale: 'en' },
        },
      },
    ]);

    const index = makePagefindAdapter({
      indexTag: 'pagefind-quilty',
      loadModule: async () => mock.module,
    });
    await index.search('p');
    expect(mock.optionsSpy).toHaveBeenCalledWith({
      baseFilters: { 'pagefind-tag': 'pagefind-quilty' },
    });
  });

  it('translates port-shape filters to Pagefind filter shape', async () => {
    const mock = makeMockPagefind([]);

    const index = makePagefindAdapter({ loadModule: async () => mock.module });
    await index.search('q', {
      filters: [
        { field: 'category', equals: 'blog' },
        { field: 'locale', equals: 'en' },
      ],
    });
    expect(mock.searchSpy).toHaveBeenCalledWith('q', {
      filters: {
        category: { equals: 'blog' },
        locale: { equals: 'en' },
      },
    });
  });

  it('synthesises descending scores from result position', async () => {
    const mock = makeMockPagefind(
      Array.from({ length: 5 }, (_, i) => ({
        id: `r-${i}`,
        data: {
          url: `/r${i}`,
          excerpt: 'e',
          meta: { title: `R${i}`, category: 'blog', locale: 'en' },
        },
      })),
    );

    const index = makePagefindAdapter({ loadModule: async () => mock.module });
    const r = await index.search('R');
    expect(r.total).toBe(5);
    for (let i = 0; i < 4; i += 1) {
      const cur = r.hits[i];
      const next = r.hits[i + 1];
      if (!cur || !next) throw new Error(`hit pair missing at i=${i}`);
      expect(cur.score).toBeGreaterThan(next.score);
    }
    const first = r.hits[0];
    const last = r.hits[r.hits.length - 1];
    if (!first || !last) throw new Error('first/last hit missing');
    expect(first.score).toBe(1);
    expect(last.score).toBeLessThan(1);
  });

  it('prefers raw_url over url for the hit URL', async () => {
    const mock = makeMockPagefind([
      {
        id: 'url-pref',
        data: {
          url: '/_next/url/canonical',
          raw_url: '/en/canonical',
          excerpt: 'e',
          meta: { title: 'U', category: 'page', locale: 'en' },
        },
      },
    ]);

    const index = makePagefindAdapter({ loadModule: async () => mock.module });
    const r = await index.search('U');
    expect(r.hits[0]?.url).toBe('/en/canonical');
  });

  it('empty query returns zero hits without invoking the loader', async () => {
    const mock = makeMockPagefind([]);
    const loadModule = vi.fn(async () => mock.module);

    const index = makePagefindAdapter({ loadModule });
    const r = await index.search('');
    expect(r.hits).toHaveLength(0);
    expect(r.total).toBe(0);
    expect(loadModule).not.toHaveBeenCalled();
    expect(mock.searchSpy).not.toHaveBeenCalled();
  });

  it('uses GLOBAL index for score — page 2 results are NOT score-tied to page 1 results', async () => {
    // 25 results × pageSize 10 → page 1: indices 0-9; page 2:
    // indices 10-19. Score formula = 1 - globalIndex/total. Page 1's
    // first hit should score 1.0; page 2's first hit should score
    // ~0.6 (= 1 - 10/25). The bug was using slice-relative index,
    // making page 2's first hit also score 1.0 — wrong.
    const mock = makeMockPagefind(
      Array.from({ length: 25 }, (_, i) => ({
        id: `r-${String(i).padStart(2, '0')}`,
        data: {
          url: `/r${i}`,
          excerpt: 'e',
          meta: { title: `R${i}`, category: 'blog', locale: 'en' },
        },
      })),
    );

    const index = makePagefindAdapter({ loadModule: async () => mock.module });
    const page1 = await index.search('R', { page: 1, pageSize: 10 });
    const page2 = await index.search('R', { page: 2, pageSize: 10 });

    const page1Top = page1.hits[0];
    const page1Last = page1.hits[page1.hits.length - 1];
    const page2Top = page2.hits[0];
    if (!page1Top || !page1Last || !page2Top) throw new Error('paginated hits missing');
    expect(page1Top.score).toBe(1);
    // Page 2's first hit is global index 10; score = 1 - 10/25 = 0.6
    expect(page2Top.score).toBeCloseTo(0.6, 5);
    // Scores monotonically decrease across pages.
    expect(page2Top.score).toBeLessThan(page1Last.score);
  });

  it('clamps score to [0, 1] under pathological pagination overshoot', async () => {
    // Even if pageSize × page > totalResults the slice is empty, but
    // the formula should never produce a negative score regardless.
    const mock = makeMockPagefind([
      {
        id: 'only',
        data: {
          url: '/o',
          excerpt: 'e',
          meta: { title: 'O', category: 'page', locale: 'en' },
        },
      },
    ]);

    const index = makePagefindAdapter({ loadModule: async () => mock.module });
    const r = await index.search('O', { page: 1, pageSize: 10 });
    for (const hit of r.hits) {
      expect(hit.score).toBeGreaterThanOrEqual(0);
      expect(hit.score).toBeLessThanOrEqual(1);
    }
  });

  it('re-checks abort signal AFTER loader resolves (last cancellation gate)', async () => {
    // The loader resolves slowly; the caller aborts during the load.
    // The adapter must surface AbortError without invoking the
    // (uncancellable) Pagefind search() call.
    const mock = makeMockPagefind([]);
    const controller = new AbortController();
    const loadModule = vi.fn(async () => {
      controller.abort();
      return mock.module;
    });

    const index = makePagefindAdapter({ loadModule });
    await expect(index.search('q', { signal: controller.signal })).rejects.toMatchObject({
      name: 'AbortError',
    });
    // Loader DID run (the test simulates abort mid-load); Pagefind
    // search did NOT run.
    expect(loadModule).toHaveBeenCalledTimes(1);
    expect(mock.searchSpy).not.toHaveBeenCalled();
  });

  it('aborts on pre-aborted signal without invoking the loader', async () => {
    const mock = makeMockPagefind([]);
    const loadModule = vi.fn(async () => mock.module);

    const controller = new AbortController();
    controller.abort();
    const index = makePagefindAdapter({ loadModule });
    await expect(index.search('q', { signal: controller.signal })).rejects.toMatchObject({
      name: 'AbortError',
    });
    expect(loadModule).not.toHaveBeenCalled();
  });
});
